services:
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orchestrator
    ports:
      - "50051:50051"
    environment:
      - COLLISION_SERVICE_ADDR=collision-service:50053
      - ORBIT_SERVICE_ADDR=orbit-service:50052
    networks:
      - astro-net
    depends_on:
      - collision-service
      - orbit-service
    command: ["orchestrator"]

  collision-service:
    build:
      context: .
      dockerfile: collision-service/Dockerfile
    ports:
      - "50053:50053"
    networks:
      - astro-net

  orbit-service:
    build:
      context: .
      dockerfile: orbit-service/Dockerfile
    container_name: orbit-service
    environment:
      - PYTHONPATH=/app/proto
    ports:
      - "50052:50052"
    networks:
      - astro-net
    command: ["python", "orbit_service.py"]
networks:
  astro-net:
    driver: bridge