# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: astro.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'astro.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61stro.proto\x12\x05\x61stro\"\x83\x01\n\x0bObservation\x12\x10\n\x08obs_time\x18\x01 \x01(\t\x12\x0e\n\x06ra_deg\x18\x02 \x01(\x01\x12\x0f\n\x07\x64\x65\x63_deg\x18\x03 \x01(\x01\x12\x0e\n\x06rms_ra\x18\x04 \x01(\x01\x12\x0f\n\x07rms_dec\x18\x05 \x01(\x01\x12\x0f\n\x07station\x18\x06 \x01(\t\x12\x0f\n\x07\x63\x61talog\x18\x07 \x01(\t\"h\n\x13ObservationsRequest\x12(\n\x0cobservations\x18\x01 \x03(\x0b\x32\x12.astro.Observation\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x13\n\x0bobject_name\x18\x03 \x01(\t\"~\n\rOrbitElements\x12\x0c\n\x04\x61_au\x18\x01 \x01(\x01\x12\t\n\x01\x65\x18\x02 \x01(\x01\x12\r\n\x05i_deg\x18\x03 \x01(\x01\x12\x11\n\tomega_deg\x18\x04 \x01(\x01\x12\x14\n\x0c\x62ig_mega_deg\x18\x05 \x01(\x01\x12\r\n\x05m_deg\x18\x06 \x01(\x01\x12\r\n\x05\x65poch\x18\x07 \x01(\t\"k\n\rCollisionRisk\x12\x15\n\rperihelion_au\x18\x01 \x01(\x01\x12\x15\n\rmoid_earth_au\x18\x02 \x01(\x01\x12\x18\n\x10potential_impact\x18\x03 \x01(\x08\x12\x12\n\nrisk_level\x18\x04 \x01(\t\"h\n\rOrbitResponse\x12#\n\x05orbit\x18\x01 \x01(\x0b\x32\x14.astro.OrbitElements\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"\x8b\x01\n\x0cRiskResponse\x12\"\n\x04risk\x18\x01 \x01(\x0b\x32\x14.astro.CollisionRisk\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12#\n\x05orbit\x18\x05 \x01(\x0b\x32\x14.astro.OrbitElements2M\n\x0cOrbitService\x12=\n\tCalculate\x12\x1a.astro.ObservationsRequest\x1a\x14.astro.OrbitResponse2K\n\x10\x43ollisionService\x12\x37\n\nAssessRisk\x12\x14.astro.OrbitElements\x1a\x13.astro.RiskResponse2Q\n\x13OrchestratorService\x12:\n\x07Process\x12\x1a.astro.ObservationsRequest\x1a\x13.astro.RiskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'astro_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBSERVATION']._serialized_start=23
  _globals['_OBSERVATION']._serialized_end=154
  _globals['_OBSERVATIONSREQUEST']._serialized_start=156
  _globals['_OBSERVATIONSREQUEST']._serialized_end=260
  _globals['_ORBITELEMENTS']._serialized_start=262
  _globals['_ORBITELEMENTS']._serialized_end=388
  _globals['_COLLISIONRISK']._serialized_start=390
  _globals['_COLLISIONRISK']._serialized_end=497
  _globals['_ORBITRESPONSE']._serialized_start=499
  _globals['_ORBITRESPONSE']._serialized_end=603
  _globals['_RISKRESPONSE']._serialized_start=606
  _globals['_RISKRESPONSE']._serialized_end=745
  _globals['_ORBITSERVICE']._serialized_start=747
  _globals['_ORBITSERVICE']._serialized_end=824
  _globals['_COLLISIONSERVICE']._serialized_start=826
  _globals['_COLLISIONSERVICE']._serialized_end=901
  _globals['_ORCHESTRATORSERVICE']._serialized_start=903
  _globals['_ORCHESTRATORSERVICE']._serialized_end=984
# @@protoc_insertion_point(module_scope)
