// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: astro.proto

#include "astro.pb.h"
#include "astro.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace astro {

static const char* OrbitService_method_names[] = {
  "/astro.OrbitService/Calculate",
};

std::unique_ptr< OrbitService::Stub> OrbitService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< OrbitService::Stub> stub(new OrbitService::Stub(channel, options));
  return stub;
}

OrbitService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Calculate_(OrbitService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status OrbitService::Stub::Calculate(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::astro::OrbitResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::astro::ObservationsRequest, ::astro::OrbitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Calculate_, context, request, response);
}

void OrbitService::Stub::async::Calculate(::grpc::ClientContext* context, const ::astro::ObservationsRequest* request, ::astro::OrbitResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::astro::ObservationsRequest, ::astro::OrbitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Calculate_, context, request, response, std::move(f));
}

void OrbitService::Stub::async::Calculate(::grpc::ClientContext* context, const ::astro::ObservationsRequest* request, ::astro::OrbitResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Calculate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::astro::OrbitResponse>* OrbitService::Stub::PrepareAsyncCalculateRaw(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::astro::OrbitResponse, ::astro::ObservationsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Calculate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::astro::OrbitResponse>* OrbitService::Stub::AsyncCalculateRaw(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCalculateRaw(context, request, cq);
  result->StartCall();
  return result;
}

OrbitService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrbitService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrbitService::Service, ::astro::ObservationsRequest, ::astro::OrbitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OrbitService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::astro::ObservationsRequest* req,
             ::astro::OrbitResponse* resp) {
               return service->Calculate(ctx, req, resp);
             }, this)));
}

OrbitService::Service::~Service() {
}

::grpc::Status OrbitService::Service::Calculate(::grpc::ServerContext* context, const ::astro::ObservationsRequest* request, ::astro::OrbitResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* CollisionService_method_names[] = {
  "/astro.CollisionService/AssessRisk",
};

std::unique_ptr< CollisionService::Stub> CollisionService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CollisionService::Stub> stub(new CollisionService::Stub(channel, options));
  return stub;
}

CollisionService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_AssessRisk_(CollisionService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CollisionService::Stub::AssessRisk(::grpc::ClientContext* context, const ::astro::OrbitElements& request, ::astro::RiskResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::astro::OrbitElements, ::astro::RiskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AssessRisk_, context, request, response);
}

void CollisionService::Stub::async::AssessRisk(::grpc::ClientContext* context, const ::astro::OrbitElements* request, ::astro::RiskResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::astro::OrbitElements, ::astro::RiskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AssessRisk_, context, request, response, std::move(f));
}

void CollisionService::Stub::async::AssessRisk(::grpc::ClientContext* context, const ::astro::OrbitElements* request, ::astro::RiskResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AssessRisk_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::astro::RiskResponse>* CollisionService::Stub::PrepareAsyncAssessRiskRaw(::grpc::ClientContext* context, const ::astro::OrbitElements& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::astro::RiskResponse, ::astro::OrbitElements, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AssessRisk_, context, request);
}

::grpc::ClientAsyncResponseReader< ::astro::RiskResponse>* CollisionService::Stub::AsyncAssessRiskRaw(::grpc::ClientContext* context, const ::astro::OrbitElements& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAssessRiskRaw(context, request, cq);
  result->StartCall();
  return result;
}

CollisionService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CollisionService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CollisionService::Service, ::astro::OrbitElements, ::astro::RiskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CollisionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::astro::OrbitElements* req,
             ::astro::RiskResponse* resp) {
               return service->AssessRisk(ctx, req, resp);
             }, this)));
}

CollisionService::Service::~Service() {
}

::grpc::Status CollisionService::Service::AssessRisk(::grpc::ServerContext* context, const ::astro::OrbitElements* request, ::astro::RiskResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* OrchestratorService_method_names[] = {
  "/astro.OrchestratorService/Process",
};

std::unique_ptr< OrchestratorService::Stub> OrchestratorService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< OrchestratorService::Stub> stub(new OrchestratorService::Stub(channel, options));
  return stub;
}

OrchestratorService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Process_(OrchestratorService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status OrchestratorService::Stub::Process(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::astro::RiskResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::astro::ObservationsRequest, ::astro::RiskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Process_, context, request, response);
}

void OrchestratorService::Stub::async::Process(::grpc::ClientContext* context, const ::astro::ObservationsRequest* request, ::astro::RiskResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::astro::ObservationsRequest, ::astro::RiskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Process_, context, request, response, std::move(f));
}

void OrchestratorService::Stub::async::Process(::grpc::ClientContext* context, const ::astro::ObservationsRequest* request, ::astro::RiskResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Process_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::astro::RiskResponse>* OrchestratorService::Stub::PrepareAsyncProcessRaw(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::astro::RiskResponse, ::astro::ObservationsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Process_, context, request);
}

::grpc::ClientAsyncResponseReader< ::astro::RiskResponse>* OrchestratorService::Stub::AsyncProcessRaw(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncProcessRaw(context, request, cq);
  result->StartCall();
  return result;
}

OrchestratorService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrchestratorService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrchestratorService::Service, ::astro::ObservationsRequest, ::astro::RiskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OrchestratorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::astro::ObservationsRequest* req,
             ::astro::RiskResponse* resp) {
               return service->Process(ctx, req, resp);
             }, this)));
}

OrchestratorService::Service::~Service() {
}

::grpc::Status OrchestratorService::Service::Process(::grpc::ServerContext* context, const ::astro::ObservationsRequest* request, ::astro::RiskResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace astro
#include <grpcpp/ports_undef.inc>

