// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: astro.proto
#ifndef GRPC_astro_2eproto__INCLUDED
#define GRPC_astro_2eproto__INCLUDED

#include "astro.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace astro {

// ====================== Сервисы ======================
class OrbitService final {
 public:
  static constexpr char const* service_full_name() {
    return "astro.OrbitService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Calculate(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::astro::OrbitResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::astro::OrbitResponse>> AsyncCalculate(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::astro::OrbitResponse>>(AsyncCalculateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::astro::OrbitResponse>> PrepareAsyncCalculate(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::astro::OrbitResponse>>(PrepareAsyncCalculateRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Calculate(::grpc::ClientContext* context, const ::astro::ObservationsRequest* request, ::astro::OrbitResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Calculate(::grpc::ClientContext* context, const ::astro::ObservationsRequest* request, ::astro::OrbitResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::astro::OrbitResponse>* AsyncCalculateRaw(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::astro::OrbitResponse>* PrepareAsyncCalculateRaw(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Calculate(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::astro::OrbitResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::astro::OrbitResponse>> AsyncCalculate(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::astro::OrbitResponse>>(AsyncCalculateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::astro::OrbitResponse>> PrepareAsyncCalculate(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::astro::OrbitResponse>>(PrepareAsyncCalculateRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Calculate(::grpc::ClientContext* context, const ::astro::ObservationsRequest* request, ::astro::OrbitResponse* response, std::function<void(::grpc::Status)>) override;
      void Calculate(::grpc::ClientContext* context, const ::astro::ObservationsRequest* request, ::astro::OrbitResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::astro::OrbitResponse>* AsyncCalculateRaw(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::astro::OrbitResponse>* PrepareAsyncCalculateRaw(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Calculate_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Calculate(::grpc::ServerContext* context, const ::astro::ObservationsRequest* request, ::astro::OrbitResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Calculate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Calculate() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Calculate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Calculate(::grpc::ServerContext* /*context*/, const ::astro::ObservationsRequest* /*request*/, ::astro::OrbitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCalculate(::grpc::ServerContext* context, ::astro::ObservationsRequest* request, ::grpc::ServerAsyncResponseWriter< ::astro::OrbitResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Calculate<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Calculate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Calculate() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::astro::ObservationsRequest, ::astro::OrbitResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::astro::ObservationsRequest* request, ::astro::OrbitResponse* response) { return this->Calculate(context, request, response); }));}
    void SetMessageAllocatorFor_Calculate(
        ::grpc::MessageAllocator< ::astro::ObservationsRequest, ::astro::OrbitResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::astro::ObservationsRequest, ::astro::OrbitResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Calculate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Calculate(::grpc::ServerContext* /*context*/, const ::astro::ObservationsRequest* /*request*/, ::astro::OrbitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Calculate(
      ::grpc::CallbackServerContext* /*context*/, const ::astro::ObservationsRequest* /*request*/, ::astro::OrbitResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Calculate<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Calculate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Calculate() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Calculate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Calculate(::grpc::ServerContext* /*context*/, const ::astro::ObservationsRequest* /*request*/, ::astro::OrbitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Calculate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Calculate() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Calculate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Calculate(::grpc::ServerContext* /*context*/, const ::astro::ObservationsRequest* /*request*/, ::astro::OrbitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCalculate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Calculate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Calculate() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Calculate(context, request, response); }));
    }
    ~WithRawCallbackMethod_Calculate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Calculate(::grpc::ServerContext* /*context*/, const ::astro::ObservationsRequest* /*request*/, ::astro::OrbitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Calculate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Calculate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Calculate() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::astro::ObservationsRequest, ::astro::OrbitResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::astro::ObservationsRequest, ::astro::OrbitResponse>* streamer) {
                       return this->StreamedCalculate(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Calculate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Calculate(::grpc::ServerContext* /*context*/, const ::astro::ObservationsRequest* /*request*/, ::astro::OrbitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCalculate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::astro::ObservationsRequest,::astro::OrbitResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Calculate<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Calculate<Service > StreamedService;
};

class CollisionService final {
 public:
  static constexpr char const* service_full_name() {
    return "astro.CollisionService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status AssessRisk(::grpc::ClientContext* context, const ::astro::OrbitElements& request, ::astro::RiskResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::astro::RiskResponse>> AsyncAssessRisk(::grpc::ClientContext* context, const ::astro::OrbitElements& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::astro::RiskResponse>>(AsyncAssessRiskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::astro::RiskResponse>> PrepareAsyncAssessRisk(::grpc::ClientContext* context, const ::astro::OrbitElements& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::astro::RiskResponse>>(PrepareAsyncAssessRiskRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void AssessRisk(::grpc::ClientContext* context, const ::astro::OrbitElements* request, ::astro::RiskResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AssessRisk(::grpc::ClientContext* context, const ::astro::OrbitElements* request, ::astro::RiskResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::astro::RiskResponse>* AsyncAssessRiskRaw(::grpc::ClientContext* context, const ::astro::OrbitElements& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::astro::RiskResponse>* PrepareAsyncAssessRiskRaw(::grpc::ClientContext* context, const ::astro::OrbitElements& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AssessRisk(::grpc::ClientContext* context, const ::astro::OrbitElements& request, ::astro::RiskResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::astro::RiskResponse>> AsyncAssessRisk(::grpc::ClientContext* context, const ::astro::OrbitElements& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::astro::RiskResponse>>(AsyncAssessRiskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::astro::RiskResponse>> PrepareAsyncAssessRisk(::grpc::ClientContext* context, const ::astro::OrbitElements& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::astro::RiskResponse>>(PrepareAsyncAssessRiskRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AssessRisk(::grpc::ClientContext* context, const ::astro::OrbitElements* request, ::astro::RiskResponse* response, std::function<void(::grpc::Status)>) override;
      void AssessRisk(::grpc::ClientContext* context, const ::astro::OrbitElements* request, ::astro::RiskResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::astro::RiskResponse>* AsyncAssessRiskRaw(::grpc::ClientContext* context, const ::astro::OrbitElements& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::astro::RiskResponse>* PrepareAsyncAssessRiskRaw(::grpc::ClientContext* context, const ::astro::OrbitElements& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AssessRisk_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status AssessRisk(::grpc::ServerContext* context, const ::astro::OrbitElements* request, ::astro::RiskResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AssessRisk : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AssessRisk() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AssessRisk() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AssessRisk(::grpc::ServerContext* /*context*/, const ::astro::OrbitElements* /*request*/, ::astro::RiskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAssessRisk(::grpc::ServerContext* context, ::astro::OrbitElements* request, ::grpc::ServerAsyncResponseWriter< ::astro::RiskResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AssessRisk<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AssessRisk : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AssessRisk() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::astro::OrbitElements, ::astro::RiskResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::astro::OrbitElements* request, ::astro::RiskResponse* response) { return this->AssessRisk(context, request, response); }));}
    void SetMessageAllocatorFor_AssessRisk(
        ::grpc::MessageAllocator< ::astro::OrbitElements, ::astro::RiskResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::astro::OrbitElements, ::astro::RiskResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AssessRisk() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AssessRisk(::grpc::ServerContext* /*context*/, const ::astro::OrbitElements* /*request*/, ::astro::RiskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AssessRisk(
      ::grpc::CallbackServerContext* /*context*/, const ::astro::OrbitElements* /*request*/, ::astro::RiskResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AssessRisk<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AssessRisk : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AssessRisk() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AssessRisk() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AssessRisk(::grpc::ServerContext* /*context*/, const ::astro::OrbitElements* /*request*/, ::astro::RiskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AssessRisk : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AssessRisk() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AssessRisk() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AssessRisk(::grpc::ServerContext* /*context*/, const ::astro::OrbitElements* /*request*/, ::astro::RiskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAssessRisk(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AssessRisk : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AssessRisk() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AssessRisk(context, request, response); }));
    }
    ~WithRawCallbackMethod_AssessRisk() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AssessRisk(::grpc::ServerContext* /*context*/, const ::astro::OrbitElements* /*request*/, ::astro::RiskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AssessRisk(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AssessRisk : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AssessRisk() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::astro::OrbitElements, ::astro::RiskResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::astro::OrbitElements, ::astro::RiskResponse>* streamer) {
                       return this->StreamedAssessRisk(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AssessRisk() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AssessRisk(::grpc::ServerContext* /*context*/, const ::astro::OrbitElements* /*request*/, ::astro::RiskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAssessRisk(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::astro::OrbitElements,::astro::RiskResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AssessRisk<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AssessRisk<Service > StreamedService;
};

class OrchestratorService final {
 public:
  static constexpr char const* service_full_name() {
    return "astro.OrchestratorService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Один публичный метод — всё остальное внутри
    virtual ::grpc::Status Process(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::astro::RiskResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::astro::RiskResponse>> AsyncProcess(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::astro::RiskResponse>>(AsyncProcessRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::astro::RiskResponse>> PrepareAsyncProcess(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::astro::RiskResponse>>(PrepareAsyncProcessRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Один публичный метод — всё остальное внутри
      virtual void Process(::grpc::ClientContext* context, const ::astro::ObservationsRequest* request, ::astro::RiskResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Process(::grpc::ClientContext* context, const ::astro::ObservationsRequest* request, ::astro::RiskResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::astro::RiskResponse>* AsyncProcessRaw(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::astro::RiskResponse>* PrepareAsyncProcessRaw(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Process(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::astro::RiskResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::astro::RiskResponse>> AsyncProcess(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::astro::RiskResponse>>(AsyncProcessRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::astro::RiskResponse>> PrepareAsyncProcess(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::astro::RiskResponse>>(PrepareAsyncProcessRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Process(::grpc::ClientContext* context, const ::astro::ObservationsRequest* request, ::astro::RiskResponse* response, std::function<void(::grpc::Status)>) override;
      void Process(::grpc::ClientContext* context, const ::astro::ObservationsRequest* request, ::astro::RiskResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::astro::RiskResponse>* AsyncProcessRaw(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::astro::RiskResponse>* PrepareAsyncProcessRaw(::grpc::ClientContext* context, const ::astro::ObservationsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Process_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Один публичный метод — всё остальное внутри
    virtual ::grpc::Status Process(::grpc::ServerContext* context, const ::astro::ObservationsRequest* request, ::astro::RiskResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Process : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Process() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Process() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Process(::grpc::ServerContext* /*context*/, const ::astro::ObservationsRequest* /*request*/, ::astro::RiskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcess(::grpc::ServerContext* context, ::astro::ObservationsRequest* request, ::grpc::ServerAsyncResponseWriter< ::astro::RiskResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Process<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Process : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Process() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::astro::ObservationsRequest, ::astro::RiskResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::astro::ObservationsRequest* request, ::astro::RiskResponse* response) { return this->Process(context, request, response); }));}
    void SetMessageAllocatorFor_Process(
        ::grpc::MessageAllocator< ::astro::ObservationsRequest, ::astro::RiskResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::astro::ObservationsRequest, ::astro::RiskResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Process() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Process(::grpc::ServerContext* /*context*/, const ::astro::ObservationsRequest* /*request*/, ::astro::RiskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Process(
      ::grpc::CallbackServerContext* /*context*/, const ::astro::ObservationsRequest* /*request*/, ::astro::RiskResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Process<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Process : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Process() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Process() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Process(::grpc::ServerContext* /*context*/, const ::astro::ObservationsRequest* /*request*/, ::astro::RiskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Process : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Process() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Process() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Process(::grpc::ServerContext* /*context*/, const ::astro::ObservationsRequest* /*request*/, ::astro::RiskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcess(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Process : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Process() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Process(context, request, response); }));
    }
    ~WithRawCallbackMethod_Process() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Process(::grpc::ServerContext* /*context*/, const ::astro::ObservationsRequest* /*request*/, ::astro::RiskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Process(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Process : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Process() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::astro::ObservationsRequest, ::astro::RiskResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::astro::ObservationsRequest, ::astro::RiskResponse>* streamer) {
                       return this->StreamedProcess(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Process() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Process(::grpc::ServerContext* /*context*/, const ::astro::ObservationsRequest* /*request*/, ::astro::RiskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedProcess(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::astro::ObservationsRequest,::astro::RiskResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Process<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Process<Service > StreamedService;
};

}  // namespace astro


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_astro_2eproto__INCLUDED
